[package]
name = "image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
image = "0.25"
libloading = "0.9.0"
log = "0.4"
env_logger = "0.11"
anyhow = "1"
